# Zjazd 3, część 1 — NumPy
**Autor:** Miłosz

In [45]:
import numpy as np

In [46]:
# Dane
dane = np.array([
    [120, 145, 167],   # Produkt A
    [89,  102, 95],    # Produkt B
    [234, 267, 289],   # Produkt C
    [56,  78,  91],    # Produkt D
])

produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

# 1. Sprzedaż Produktu A w Q2
print("Produkt A, Q2:", dane[0, 1])

# 2. Cała sprzedaż Produktu C
print("Produkt C (wszystkie kwartały):", dane[2])

# 3. Sprzedaż wszystkich produktów w Q1
print("Wszystkie produkty, Q1:", dane[:, 0])

# 4. Produkty B i C w Q2 i Q3
print("Produkty B i C, Q2-Q3:")
print(dane[1:3, 1:3])

Produkt A, Q2: 145
Produkt C (wszystkie kwartały): [234 267 289]
Wszystkie produkty, Q1: [120  89 234  56]
Produkty B i C, Q2-Q3:
[[102  95]
 [267 289]]


In [47]:
# Produkty w sklepie internetowym
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
         'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']

ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

In [48]:
srednia = ceny.mean()
najdrozszy = ceny.max()
najtanszy = ceny.min()

idx_max = ceny.argmax()
idx_min = ceny.argmin()

print("Średnia cena:", srednia)
print("Najdroższy:", nazwy[idx_max], "-", najdrozszy)
print("Najtańszy:", nazwy[idx_min], "-", najtanszy)

Średnia cena: 1171.0
Najdroższy: Laptop - 3499
Najtańszy: Ładowarka - 89


In [49]:
wartosci = ceny * ilosci_magazyn
laczna_wartosc = wartosci.sum()

print("Wartość każdego produktu:", wartosci)
print("Łączna wartość magazynu:", laczna_wartosc)

Wartość każdego produktu: [ 52485  79758 194922  54444  27768  22161  25929  34477  26955  30566]
Łączna wartość magazynu: 549465


In [50]:
ceny_rabat = ceny * 0.85

ceny_vat = ceny * 1.23

ile_drogich = (ceny > 1000).sum()

print("Ceny po rabacie:", ceny_rabat)
print("Ceny z VAT:", ceny_vat)
print("Liczba produktów > 1000 zł:", ile_drogich)

Ceny po rabacie: [2974.15 1614.15 2124.15  296.65   75.65  211.65  109.65 1274.15  509.15
  764.15]
Ceny z VAT: [4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77]
Liczba produktów > 1000 zł: 4


In [51]:
nazwy_np = np.array(nazwy)

maska_oceny = oceny_klientow >= 4.5
print("Produkty z oceną >= 4.5:")
print(nazwy_np[maska_oceny])
print(ceny[maska_oceny])

maska_tanie = ceny < 200
print("\nProdukty < 200 zł:")
print(nazwy_np[maska_tanie])
print(ilosci_magazyn[maska_tanie])

Produkty z oceną >= 4.5:
['Laptop' 'Smartfon' 'Słuchawki' 'Monitor']
[3499 2499  349 1499]

Produkty < 200 zł:
['Ładowarka' 'Mysz']
[312 201]


In [52]:
nazwy_np = np.array(nazwy)
wartosci = ceny * ilosci_magazyn

maska_niski = ilosci_magazyn < 30

produkty_niski = nazwy_np[maska_niski]
wartosc_niski = wartosci[maska_niski].sum()

procent = (wartosc_niski / wartosci.sum()) * 100

print("Produkty z niskim stanem:", produkty_niski)
print("Łączna wartość:", wartosc_niski)
print("Udział %:", procent)

Produkty z niskim stanem: ['Laptop' 'Monitor']
Łączna wartość: 86962
Udział %: 15.826667758637946


## Wnioski z benchmarku
- NumPy jest **24×** szybszy w mnożeniu
- NumPy jest **31×** szybszy w sumowaniu
- NumPy jest **24×** szybszy w filtrowaniu
- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list

In [53]:
import time

# Przygotowanie danych
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

# Test 1: Pomnóż przez 2
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start

start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start

print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista:  71.9 ms
NumPy:  3.0 ms
NumPy jest 24× szybszy!


In [54]:
# Test 2: Suma
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start

start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start

print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Suma (1,000,000 elementów) ===
Lista:  27.1 ms
NumPy:  1.0 ms
NumPy jest 28× szybszy!


In [55]:
# Test 3: Filtrowanie (elementy > 500000)
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start

start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start

print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista:  39.4 ms
NumPy:  2.4 ms
NumPy jest 17× szybszy!


In [56]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])

# 1. Sprzedaż w styczniu
print("Styczeń:", miesiace_sprzedaz[0])

# 2. Sprzedaż w grudniu
print("Grudzień:", miesiace_sprzedaz[-1])

# 3. Sprzedaż w Q1 (styczeń–marzec)
print("Q1:", miesiace_sprzedaz[0:3])

# 4. Sprzedaż w Q4 (październik–grudzień)
print("Q4:", miesiace_sprzedaz[-3:])

# 5. Sprzedaż co drugi miesiąc
print("Co drugi miesiąc:", miesiace_sprzedaz[::2])

# 6. Sprzedaż od tyłu
print("Od tyłu:", miesiace_sprzedaz[::-1])

Styczeń: 120
Grudzień: 221
Q1: [120 135  98]
Q4: [143 198 221]
Co drugi miesiąc: [120  98 167 201 156 198]
Od tyłu: [221 198 143 156 178 201 189 167 142  98 135 120]


In [57]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy:                     0     1    2    3    4    5    6    7    8    9   10   11
# Miesiące:                  Sty  Lut  Mar  Kwi  Maj  Cze  Lip  Sie  Wrz  Paź  Lis  Gru

In [58]:
# 1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [59]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [60]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [61]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [62]:
# 5. 7 równomiernych punktów od 0 do 1
procenty = np.linspace(0, 1, 7)
print(f"Procenty: {procenty}")

Procenty: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [63]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [64]:
# Zbadaj tablicę losowych ocen
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


In [65]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
    [120, 145, 167],   # Produkt A
    [89,  102, 95],    # Produkt B
    [234, 267, 289],   # Produkt C
    [56,  78,  91],    # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']